<a href="https://colab.research.google.com/github/azkbrqlna/2025-AI-Praktikum/blob/main/Jobsheet2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Jobsheet 2 : OPERASI MATEMATIKA, VEKTOR, MATRIKS DAN TIPE DATA

## Operasi Matematika Menggunakan Python

### a. Mendapatkan nilai Minimum dan Maksimum

In [1]:
x = min(5, 10, 25)
y = max(6, 12, 18)

print(x)
print(y)

5
18


### b. Mendapatkan nilai Absolute

In [2]:
x = abs(-7.25)

print(x)

7.25


### c. Mendapatkan nilai Pangkat

In [3]:
import math
x = math.pow(4, 3)

print(x)

64.0


### d. Mendapatkan nilai AKar

In [4]:
import math
x = math.sqrt(64)

print(x)

8.0


### e. Mendapatkan nilai Pembulatan

In [5]:
import math
x = math.ceil(1.4)
y = math.floor(1.4)

print(x)
print(y)

2
1


### f.	Mendapatkan nilai konstanta (PI)

In [6]:
import math
x = math.pi

print(x)

3.141592653589793


## Menggunakan Fungsi MATH

In [7]:
import math

# Menghitung nilai sinus dari 1 radian
a = math.sin(1)

# Menghitung nilai kosinus dari 9 radian
b = math.cos(9)

# Menghitung nilai tangen dari 5 radian
c = math.tan(5)

# Menghitung logaritma natural (basis e) dari 6
d = math.log(6)

# Menghitung logaritma basis 10 dari 6
e = math.log10(6)

# Mengkonversi 6 radian ke derajat
f = math.degrees(6)

# Menghitung jarak Euclidean antara titik (1, 2) dan (3, 4)
g = math.dist((1, 2), (3, 4))

# Menghitung faktorial dari 6 (6!)
h = math.factorial(6)

# Menghitung sisa pembagian (modulus) dari 6 dibagi 5
i = math.fmod(6, 5)

# Memeriksa apakah 6 adalah NaN (Not a Number)
j = math.isnan(6)

# Menghitung nilai fungsi gamma dari 6
k = math.gamma(6)

# Menghitung jumlah permutasi dari 6 item yang diambil 5 pada satu waktu
l = math.perm(6, 5)

print(a)
print(b)
print(c)
print(d)
print(e)
print(f)
print(g)
print(h)
print(i)
print(j)
print(k)
print(l)

0.8414709848078965
-0.9111302618846769
-3.380515006246586
1.791759469228055
0.7781512503836436
343.77467707849394
2.8284271247461903
720
1.0
False
120.0
720


## Operasi matriks dan vektor dengan python

### a.	Membuat matriks di pyhon

In [8]:
import numpy as np
A = np.array([[80, 30, 25],
[50, 20, 10]])
B = np.array([[30, 60, 15],
[10, 30, 30]])

hasil = A + B

print(hasil)

[[110  90  40]
 [ 60  50  40]]


### b.	Melakukan operasi dot product

In [9]:
import numpy as np
A = np.array([10, 20, 15])
B = np.array([16, 67, 35])

hasil = np.dot(A, B)

print(hasil)

2025


### c.	Melakukan operasi cross product

In [10]:
import numpy as np
A = np.array([10, 20, 15])
B = np.array([16, 67, 35])

Hasil = np.cross(A, B)

print(Hasil)

[-305 -110  350]


## Tugas


In [11]:
import numpy as np
import math

A = np.array([[3, 1], [2, 0]])
B = np.array([[2, 1], [1, -1]])
C = np.array([[-1, 1, 2], [2, 0, -1]])

AxB = np.dot(A, B)
BxC = np.dot(B, C)

print("Jawaban No. 1")
print("a. A x B =\n", AxB)
print("b. B x C =\n", BxC)
print()

faktorial_6 = math.factorial(6)
faktorial_8 = math.factorial(8)
faktorial_5 = math.factorial(5)

hasil = faktorial_8 / faktorial_5

print("Jawaban No. 2")
print("a. 6! =", faktorial_6)
print("b. 8! / 5! =", hasil)
print()

D = np.array([5, 3, 7])
E = np.array([12, -3, 1])

panjang_A = np.linalg.norm(D)
panjang_B = np.linalg.norm(E)

dot_product = np.dot(D, E)
cross_product = np.cross(D, E)

print("Jawaban No.3")
print("Panjang vektor A:", panjang_A)
print("Panjang vektor B:", panjang_B)
print("Perkalian dot A . B:", dot_product)
print("Perkalian cross A x B:\n", cross_product)

Jawaban No. 1
a. A x B =
 [[7 2]
 [4 2]]
b. B x C =
 [[ 0  2  3]
 [-3  1  3]]

Jawaban No. 2
a. 6! = 720
b. 8! / 5! = 336.0

Jawaban No.3
Panjang vektor A: 9.1104335791443
Panjang vektor B: 12.409673645990857
Perkalian dot A . B: 58
Perkalian cross A x B:
 [ 24  79 -51]
